/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import beans.Ingrediente;
import beans.Producto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author cadiaz
 */
public class ProductoWindows extends javax.swing.JPanel {

    /**
     * Creates new form ProductoWindows
     */
    public ProductoWindows() {
        initComponents();
        ArrayList<Ingrediente> list = new Ingrediente().getIngredientes();
        Ingrediente [] ingrediente = new Ingrediente[list.size()];
        for(int i = 0; i< list.size(); i++){
           ingrediente[i] = list.get(i);
        }
       jListIngredientes.setListData(ingrediente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextPrecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListIngredientes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonCrear = new javax.swing.JButton();

        jLabelTitulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabelTitulo.setText("Producto");

        jLabelNombre.setText("Nombre :");

        jLabelPrecio.setText("Precio :");

        jScrollPane1.setViewportView(jListIngredientes);

        jLabel1.setText("Seleccione los ingredientes :");

        jButtonCrear.setText("jButton1");
        jButtonCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCrearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNombre))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTitulo)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextPrecio)
                                        .addComponent(jTextNombre))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButtonCrear)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecio)
                    .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButtonCrear)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCrearMouseClicked
        
        List<Ingrediente> lista = jListIngredientes.getSelectedValuesList();
        
        String nombre = jTextNombre.getText().trim();
        String precio = jTextPrecio.getText().trim();
        Double newPrecio = convertir(precio);
        
        if(validate(nombre) && newPrecio != null && lista != null && !lista.isEmpty()){
            
            Producto producto = new Producto(null, nombre, newPrecio);
            
            if(!producto.existeProducto(nombre, newPrecio)){
                if(producto.crearProducto()){
                    lista.forEach((ingrediente) -> {
                        producto.agregarProductoIngrediente(producto.getIdProducto(), ingrediente.getIdIngrediente());
                    });
                    JOptionPane.showMessageDialog(this, "Producto creado exitosamente");
                } else {
                    
                }
            } else {
                JOptionPane.showMessageDialog(this, "El producto ya existe");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Datos incorrectos");
        }
        
       
    }//GEN-LAST:event_jButtonCrearMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JList<Ingrediente> jListIngredientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextPrecio;
    // End of variables declaration//GEN-END:variables

     /**
     * Valida que el campo no sea nulo o vacio
     * @param param
     * @return 
     */
    private boolean validate(String param){
        
        return !(param == null || param.equals("") || param.equals(" "));
    }
    
    private Double convertir(String number){
        
        Double d = null;
        
        try {
            d= Double.parseDouble(number);
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        }
        return d;
    }

}


